<?php header("Content-type: text/css"); ?>
<?php
	$absolute_path = __FILE__;
	$path_to_file = explode( 'wp-content', $absolute_path );
	$path_to_wp = $path_to_file[0];
	require_once( $path_to_wp.'/wp-load.php' );

	$toptoolbar_wrapper_background =  get_option('toptoolbar_wrapper_background'); 
    if ( $toptoolbar_wrapper_background == '' ) $toptoolbar_wrapper_background = '24241F';
?>
#toptoolbar-wrapper {background:#<?php echo $toptoolbar_wrapper_background; ?>;}
<?php $color = $_GET['themecolor']; ?>
<?php $secondcolor = $_GET['secondcolor']; ?>
.menu-header ul li a:hover,
.menu-header ul li a:active,
.menu-header ul li.current-menu-item a:link,
.menu-header ul li.current-menu-item a:visited,
#complex-slider-wrapper #slider-description strong,
#presentation-slider #slider-gallery li span.number,
#presentation-slider #slider-gallery li.active span.title,
#content-slider-wrapper .side-description .content a.read-more:hover,
#content-slider-wrapper .side-description .content a.read-more:active,
#anything-slider-wrapper .content a.read-more:hover,
#anything-slider-wrapper .content a.read-more:active,
#nivo-slider .nivo-controlNav a.nivo-control,
#intro h1,
#front-page-business .front-page-post h3 a:link,
#front-page-business .front-page-post h3 a:visited,
#front-page-posts .post h3 a:link,
#front-page-posts .post h3 a:visited,
#front-page-posts .post a.more-link:link,
#front-page-posts .post a.more-link:visited,
#front-page-business #front-page-bottom ul li h3 a:link,
#front-page-business #front-page-bottom ul li h3 a:visited,
#front-page-business #bottom-content-scroll ul li a.more-link:link,
#front-page-business #bottom-content-scroll ul li a.more-link:visited,
#front-page-botton-widgets div.column a:link,
#front-page-botton-widgets div.column a:visited,
#front-page-botton-widgets div.column strong,
#front-page-news #left-content .post h3 a:link,
#front-page-news #left-content .post h3 a:visited,
#front-page-news #left-content .post a.more-link:link,
#front-page-news #left-content .post a.more-link:visited,
#front-page-news #content .post a.title:link,
#front-page-news #content .post a.title:visited,
#front-page-news #left-content .post .more-link:link,
#front-page-news #left-content .post .more-link:visited,
#front-page-news #content .just-title-element a:link,
#front-page-news #content .just-title-element a:visited,
#front-page-news #content-sidebar ul li a:link,
#front-page-news #content-sidebar ul li a:visited,
#front-page-news #content-sidebar strong,
#front-page-presentation ul li a:link,
#front-page-presentation ul li a:visited,
#content h1,
#content h2,
#content h3,
#content h4,
#content h5,
#content h6,
#content table thead tr th,
#content a:link,
#content a:visited,
#content .blog-classic h2 a:link,
#content .blog-classic h2 a:visited,
#content .blog-modern h2 a:link,
#content .blog-modern h2 a:visited,
#content span.post-date strong,
#content span.post-date strong em,
#content #blog-accordion h3 a:hover,
#content #blog-accordion h3 a:active,
#content .blog-full h2 a:link,
#content .blog-full h2 a:visited,
#content .tabs ul.ui-tabs-nav li.ui-state-active a:link,
#content .tabs ul.ui-tabs-nav li.ui-state-active a:visited,
#content .tabs ul.ui-tabs-nav li a:hover,
#content .tabs ul.ui-tabs-nav li a:active,
#content .accordion .ui-accordion-header a:hover,
#content .accordion .ui-accordion-header a:active,
#content .accordion .ui-state-active a:link,
#content .accordion .ui-state-active a:visited,
#comments div.comment-header div.author,
#sidebar ul li.widget-container ul li a:hover,
#sidebar ul li.widget-container ul li a:active,
#sidebar ul li.widget_tag_cloud a:hover,
#sidebar ul li.widget_tag_cloud a:active,
#sidebar li.twitter span.tweet-content a:link,
#sidebar li.twitter span.tweet-content a:visited,
#sidebar li.twitter a.follow-url:link,
#sidebar li.twitter a.follow-url:visited,
#sidebar #calendar_wrap caption,
#sidebar #wp-calendar a:link,
#sidebar #wp-calendar a:visited,
#sidebar #wp-calendar tr th,
#sidebar .contact li a:link,
#sidebar .contact li a:visited,
#footer-tabs .tab h3,
#footer-tabs .tab li.widget-container a:link,
#footer-tabs .tab li.widget-container a:visited,
#footer-tabs .tab li.widget-container ul li a:hover,
#footer-tabs .tab li.widget-container ul li a:active,
#copyright a:link,
#copyright a:visited
{
	color: #<?php echo $color; ?>;
}
abbr{
	color: #<?php echo $color; ?> !important;
}
div.duotive-modal .pp_arrow_previous:hover,
div.duotive-modal .pp_arrow_next:hover,
div.duotive-modal a.pp_close:hover,
div.duotive-modal a.pp_expand:hover,
div.duotive-modal a.pp_contract:hover,
#toptoolbarsearch input.searchbutton:hover,
.menu-header ul.sub-menu,
.menu-header .sfHover .sf-sub-indicator,
#content-slider-wrapper .side-description .content a.read-more:link,
#content-slider-wrapper .side-description .content a.read-more:visited,
#anything-slider-wrapper .content a.read-more:link,
#anything-slider-wrapper .content a.read-more:visited,
#complex-slider-wrapper #slider-timer #slider-progress-bar,
#presentation-slider #slider-timer #slider-progress-bar,
#presentation-slider #slider-bottom-controls a#slider-scroll-left,
#presentation-slider #slider-bottom-controls a#slider-scroll-right,
#gallery-slider #slider-bottom-controls a#slider-scroll-left,
#gallery-slider #slider-bottom-controls a#slider-scroll-right,
#fullwidth-slider #slider-text #content-controls a#slider-control-up:hover,
#fullwidth-slider #slider-text #content-controls a#slider-control-down:hover,
#fullwidth-slider #slider-text #content-controls a#slider-control-play,
#fullwidth-slider #contentbox,
#front-page-business .front-page-post .more-link:hover,
#front-page-business .front-page-post .more-link:active,
#front-page-business #bottom-content-scroll .bx-pager a:hover,
#front-page-business #bottom-content-scroll .bx-pager a:active,
#front-page-business #bottom-content-scroll .bx-pager a.pager-active,
#front-page-botton-widgets div.column li.widget-container a.read-more:hover,
#front-page-botton-widgets div.column li.widget-container a.read-more:active,
#front-page-news #content-sidebar a.read-more:hover,
#front-page-news #content-sidebar a.read-more:active,
#content a.more-link:hover,
#content a.more-link:active,
#content form.jqtransformdone div.jqTransformSelectWrapper ul li a.selected,
#content form.jqtransformdone div.jqTransformSelectWrapper ul li a:hover,
#content form.jqtransformdone div.jqTransformSelectWrapper ul li a:active,
#content form.jqtransformdone .jqTransformRadioWrapper a.jqTransformChecked,
#content form.jqtransformdone .jqTransformCheckboxWrapper a.jqTransformChecked,
#content form div.jqTransformSelectWrapper div:hover a:link,
#content form div.jqTransformSelectWrapper div:hover a:visited,
#content input[type="button"]:hover,
#content input[type="submit"]:hover,
#content input[type="reset"]:hover, 
#content .accordion .ui-state-hover span.ui-icon,
#content .accordion .ui-state-active span.ui-icon,
#content table.pricing tr.buttons td a.button:hover,
#content table.pricing tr.buttons td a.button:active,
#content .portfolio-sub-pages li.current_page_item a:link,
#content .portfolio-sub-pages li.current_page_item a:visited,
#content .portfolio-sub-pages li a:hover,
#content .portfolio-sub-pages li a:active,
#content div.portfolio-two-column-slideshow .nivo-prevNav:hover,
#content div.portfolio-two-column-slideshow .nivo-nextNav:hover,
#comments div.comment-header div.reply a:hover,
#comments div.comment-header div.reply a:active,
#content .button:hover,
#content .button:active,
#respond h3 small a:hover,
#respond h3 small a:active,
#sidebar input[type="submit"]:hover,
#sidebar .sidebar-slideshow .nivo-prevNav:hover,
#sidebar .sidebar-slideshow .nivo-nextNav:hover,
#sidebar .contact .contact-icon,
#contact-page #contact-sidebar ul li span.contact-icon,
#footer-partners .bx-prev:hover,
#footer-partners .bx-prev:active,
#footer-partners .bx-next:hover,
#footer-partners .bx-next:active,
#footer-tabs .tab li.widget-container a.read-more:hover,
#footer-tabs .tab li.widget-container a.read-more:active,
#footer-tabs .tab li.widget-container input[type="submit"]:hover
{
	background-color: #<?php echo $color; ?>;
}
#content input[type="text"]:focus,
#content input[type="password"]:focus,
#content textarea:focus,
#content form div.jqTransformSelectWrapper div:hover,
#sidebar li.minigallery div.mini-gallery a:hover,
#sidebar li.minigallery div.mini-gallery a:active,
#sidebar input[type="text"]:focus,
#sidebar textarea:focus,
#footer-tabs .tab li.widget-container input[type="text"]:focus,
#footer-tabs .tab li.widget-container textarea:focus,
#complex-slider #slider-contentbox #slider-gallery a.active span,
#fullwidth-slider #slider-gallery a.active span {
	border-color: #<?php echo $color; ?>;
}
#toptoolbar .menu-toptoolbar ul li.current-menu-item a:link,
#toptoolbar .menu-toptoolbar ul li.current-menu-item a:visited,
#content-slider-wrapper .side-description .content h3,
#content-slider-wrapper .side-description .content strong,
#anything-slider-wrapper .content h3,
#anything-slider-wrapper .content strong,
#presentation-slider #slider-images-wrapper a span.title,
#gallery-slider ul#slider-main-ul li a span em,
#gallery-slider ul#slider-main-ul li a span strong,
#accordion-slider ul li div.content h3,
#accordion-slider ul li div.content a:link,
#accordion-slider ul li div.content a:visited,
#nivo-slider .nivo-caption span.title,
#nivo-slider .nivo-caption .read-more,
#sub-footer .menu-footer ul li a:hover,
#sub-footer .menu-footer ul li a:active {
	color:#<?php echo $secondcolor; ?>;
}